//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gtree {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gtree.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to Goldleaf via USB....
        /// </summary>
        internal static string ConnectingToGoldleaf {
            get {
                return ResourceManager.GetString("ConnectingToGoldleaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to USB device..
        /// </summary>
        internal static string ConnectingToUSB {
            get {
                return ResourceManager.GetString("ConnectingToUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to open Goldtree after having launched Goldleaf on your console. Waiting for connection....
        /// </summary>
        internal static string EnsureConnection {
            get {
                return ResourceManager.GetString("EnsureConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goldleaf has canceled the installation..
        /// </summary>
        internal static string GoldleafCancelledInstall {
            get {
                return ResourceManager.GetString("GoldleafCancelledInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate was sent to Goldleaf..
        /// </summary>
        internal static string GoldleafCertificateSent {
            get {
                return ResourceManager.GetString("GoldleafCertificateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was established with Goldleaf..
        /// </summary>
        internal static string GoldleafConnectionEstablished {
            get {
                return ResourceManager.GetString("GoldleafConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content was sent to Goldleaf..
        /// </summary>
        internal static string GoldleafContentSent {
            get {
                return ResourceManager.GetString("GoldleafContentSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected NSP&apos;s name was sent to Goldleaf. Waiting for install approval from Goldleaf....
        /// </summary>
        internal static string GoldleafNSPApproval {
            get {
                return ResourceManager.GetString("GoldleafNSPApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending certificate file....
        /// </summary>
        internal static string GoldleafSendingCertificate {
            get {
                return ResourceManager.GetString("GoldleafSendingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending content &apos;{0}&apos;... ({1} of {2}).
        /// </summary>
        internal static string GoldleafSendingContent {
            get {
                return ResourceManager.GetString("GoldleafSendingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending ticket file....
        /// </summary>
        internal static string GoldleafSendingTicket {
            get {
                return ResourceManager.GetString("GoldleafSendingTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goldleaf is ready for the installation. Preparing everything....
        /// </summary>
        internal static string GoldleafStartingInstall {
            get {
                return ResourceManager.GetString("GoldleafStartingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket was sent to Goldleaf..
        /// </summary>
        internal static string GoldleafTicketSent {
            get {
                return ResourceManager.GetString("GoldleafTicketSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation has finished. Press any key to close Goldtree
        ///.
        /// </summary>
        internal static string InstallationFinished {
            get {
                return ResourceManager.GetString("InstallationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred opening the selected NSP. Are you sure it&apos;s a valid NSP?.
        /// </summary>
        internal static string InvalidNSPError {
            get {
                return ResourceManager.GetString("InvalidNSPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSP / Nintendo Submission Package (*.nsp)|*.nsp.
        /// </summary>
        internal static string NSPExtension {
            get {
                return ResourceManager.GetString("NSPExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select NSP to send to Goldleaf via USB.
        /// </summary>
        internal static string NSPFileDialogTitle {
            get {
                return ResourceManager.GetString("NSPFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred selecting the NSP to be sent..
        /// </summary>
        internal static string NSPGeneralError {
            get {
                return ResourceManager.GetString("NSPGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the NSP to send to Goldleaf on the dialog..
        /// </summary>
        internal static string NSPSelect {
            get {
                return ResourceManager.GetString("NSPSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dialog was closed without selecting a NSP, or another error ocurred..
        /// </summary>
        internal static string NSPSelectError {
            get {
                return ResourceManager.GetString("NSPSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit....
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the USB device. Make sure you have Goldleaf open before running Goldtree..
        /// </summary>
        internal static string USBConnectionError {
            get {
                return ResourceManager.GetString("USBConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize the USB driver. Make sure you have Goldleaf open before running Goldtree..
        /// </summary>
        internal static string USBDriverInitError {
            get {
                return ResourceManager.GetString("USBDriverInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the USB driver. Make sure you have Goldleaf open before running Goldtree..
        /// </summary>
        internal static string USBDriverLoadError {
            get {
                return ResourceManager.GetString("USBDriverLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid command was received. Are you sure Goldleaf is active?.
        /// </summary>
        internal static string USBInvalidCommandReceived {
            get {
                return ResourceManager.GetString("USBInvalidCommandReceived", resourceCulture);
            }
        }
    }
}
