
/*

    Goldleaf - Nintendo Switch homebrew multitool, for several purposes and with several features

    Copyright 2018 - 2019 Goldleaf project, developed by XorTroll
    This project is under the terms of GPLv3 license: https://github.com/XorTroll/Goldleaf/blob/master/LICENSE

*/

#pragma once
#include <gleaf/set/Settings.hpp>

namespace gleaf::set
{
    struct Dictionary
    {
        Language DictLanguage;
        std::vector<std::string> Strings;
    };





    static const Dictionary English =
    {
        Language::English,
        {
            "Browse SD card",
            "Browse console memory",
            "USB installations",
            "Manage console contents",
            "Manage console tickets",
            "Browse the Internet",
            "Manage user accounts",
            "View console information",
            "About Goldleaf",
            "Browse the SD card's files and directories.",
            "Browse console memory's partitions' files and directories.",
            "Install NSPs via USB from Goldtree or other PC clients.",
            "Browse and navigate through all contents or titles in the console.",
            "Browse all the tickets from purchased or installed contents.",
            "Browse the Internet using the console's web applet.",
            "Select a user account and manage it.",
            "View information about the state of the console's memory and the SD card.",
            "View Goldleaf's version, run mode and logo.",
            "Cancel",
            "SD card",
            "Console memory",
            "Which partition of the console memory would you like to browse?",
            "PRODINFOF contains several test logs and other contents.",
            "NAND SAFE doesn't contain anything relevant.",
            "NAND SYSTEM contains all system titles and contents.",
            "NAND USER contains content installed to console memory.",
            "PRODINFOF",
            "NAND SAFE",
            "NAND USER",
            "NAND SYSTEM",
            "USB installation",
            "Starting USB installation...",
            "Console contents manager",
            "Select storage to browse its contents.",
            "Ticket manager",
            "Searching for imported tickets...",
            "Web applet",
            "Non-installed title Goldleaf uses WifiAuth web applet, which has less features.",
            "Select web page to browse through the web applet.",
            "The selected web page is bad formatted.",
            "An error ocurred attempting to launch the web applet:",
            "User accounts",
            "Processing user account...",
            "Console information",
            "View SD card and console memory's state.",
            "Unable to detect on which mode Goldleaf is running.",
            "Running as a homebrew NRO.",
            "Running as an installed title.",
            "Running as a HOME Menu (qlaunch) replacement.",
            "This directory is empty.",
            "Warning: console memory access",
            "Are you sure you want to write or delete content from console memory?",
            "Selected file type:",
            "NSP package",
            "NRO executable",
            "content ticket",
            "NxTheme theme",
            "NCA content",
            "NACP control data",
            "JPEG image",
            "binary",
            "text",
            "file",
            "directory",
            "File size:",
            "Install",
            "Launch",
            "Import",
            "Extract",
            "View contents",
            "Replace user icon",
            "View text",
            "View hex",
            "Copy",
            "Delete",
            "Rename",
            "File options",
            "NSP installation",
            "Where would you like to install the NSP?",
            "Console memory",
            "Would you like to ignore the required firmware version of the NSP?",
            "There isn't enough size to install the NSP.",
            "NSP contents' information:",
            "The NSP contains a regular title.",
            "The NSP contains a title update.",
            "The NSP contains DLC content.",
            "The NSP contains other kinds of content.",
            "The NSP seems to be official.",
            "The NSP seems to be a homebrew NSP.",
            "The NSP has a weird-formatted application ID.",
            "Application ID:",
            "Name:",
            "Author:",
            "Contents:",
            "The NSP has a ticket to be imported:",
            "Key generation:",
            "unknown version",
            "The NSP doesn't have a ticket.",
            "NRO launch",
            "Would you like to close Goldleaf and launch this NRO?",
            "NROs can only be launched if Goldleaf is a NRO.",
            "Ticket import",
            "Would you like to import this ticket?",
            "An error ocurred attempting to import the ticket:",
            "NxTheme install",
            "NxThemesInstaller NRO was not found. The theme cannot be installed.",
            "Unknown name",
            "Unknown author",
            "NACP control data information:",
            "Version:",
            "Asks for an user account?",
            "Yes",
            "No",
            "Yes, but but the account needs to have a Nintendo services account.",
            "Unknown value",
            "Supports taking screenshots?",
            "Supports video capture?",
            "Yes (manual)",
            "Logo type:",
            "Licensed by Nintendo",
            "Nintendo",
            "Account icon replacement",
            "Would you like to replace the icon of this account? It can be a risky action.",
            "The user's icon was successfully replaced.",
            "An error ocurred attempting to replace the account's icon:",
            "Payload launch",
            "Would you like to reboot the console launching this file as a payload?",
            "File delete",
            "Would you like to delete this file?",
            "The file was successfully deleted.",
            "Select a new name to rename the file.",
            "Another file or directory already has that name.",
            "An error ocurred attempting to rename the file.",
            "The file was successfully renamed.",
            "What would you like to do with this directory?",
            "Directory options",
            "Browse",
            "Rename directory",
            "An error ocurred attempting to rename the directory:",
            "The directory was successfully renamed.",
            "Starting copy process...",
            "A directory (and all its contents) were successfully copied.",
            "File copy",
            "Another file exists with the same name. Would you like to overwrite it?",
            "Starting NSP installation...",
            "Installing NSP:",
            "Processing application records...",
            "Starting to write contents...",
            "Writing content",
            "of",
            "The NSP was successfully installed.",
            "Starting USB NSP installation...",
            "Waiting for USB connection...",
            "Plug this console with a USB-C cable to connect it with the PC.",
            "Error connecting via USB.",
            "USB connection was detected. Waiting for a request from the PC client...",
            "USB installation",
            "This NSP was requested:",
            "Would you like to install it?",
            "Average speed:",
            "The USB installation finalized successfully. The PC client can be closed.",
            "An invalid response was received. Retry the installation.",
            "Information",
            "Meta",
            "Program",
            "Data",
            "Control",
            "Html documents",
            "Legal information",
            "Selected content's information:",
            "Content type:",
            "regular title",
            "DLC content",
            "title update",
            "system title",
            "system data content",
            "other system contents",
            "Content size:",
            "Version number:",
            "update",
            "The content was successfully removed.",
            "An error ocurred attempting to remove the content:",
            "Title NSP export",
            "This title is equal or bigger than 4GB. Do not export it if you're on FAT32.",
            "Would you like to export this title as a NSP?",
            "NAND SYSTEM titles are blocked from being removed.",
            "Would you like to remove this content?",
            "Console contents",
            "This storage doesn't seem to have any contents.",
            "Browsing contents in this storage.",
            "Game cartridge",
            "Starting title export...",
            "Accessing system ticket database...",
            "Accessing title NCA contents...",
            "Decrypting and exporting contents...",
            "Exporting contents from console memory...",
            "Building NSP from exported contents...",
            "The title was successfully exported:",
            "An error ocurred attempting to export the title:",
            "No tickets were found on this console.",
            "Ticket options",
            "Ticket information:",
            "This ticket seems to be used by an installed content.",
            "This ticket seems to be unused.",
            "Would you like to remove this ticket?",
            "Are you sure you want to remove a ticket which seems to be used?",
            "The ticket was successfully removed from this console.",
            "An error ocurred attempting to remove the ticket:",
            "Change nickname",
            "View icon",
            "Delete account",
            "An error ocurred attempting to process the account:",
            "Selected user:",
            "Change the user's nickname",
            "The account's nickname was changed to",
            "An error ocurred attempting to rename the account:",
            "User account",
            "This icon has been exported here:",
            "Would you like to delete this account?",
            "The account was successfully deleted.",
            "An error ocurred attempting to delete the account:",
            "free",
            "Clipboard",
            "Would you like to paste the clipboard's content here?",
            "There is nothing selected to be copied.",
            "Select name to create a new file",
            "Another file or directory already has this name.",
            "A file was created:",
            "A directory was created:",
            "Reboot or shut down",
            "Would you like to reboot or shut down the console?",
            "A file or directory was copied. The clipboard was updated.",
            "Reboot",
            "Shut down",
            "Ok",
            "Title key;",
            "Signature type:",
            "Directory size:",
            "Select a new name to rename the file.",
            "Overwrite",
            "The file was successfully copied.",
            "Connection was established. Waiting for a NSP request from PC client...",
            "The PC client has finalized the connection.",
            "Content information",
            "Export",
            "Remove",
            "The content was successfully removed.",
            "An error ocurred attempting to remove the content:",
            "Browse both common and personalized tickets.",
            "An error ocurred attempting to rename the account: The name was too long.",
            "Select name to create a new directory.",
            "An error ocurred attempting to install the NSP:", // New (translate this and below to other langs!)
            "An error ocurred attempting to find NxThemesInstaller NRO:",
            "An error ocurred attempting to delete the file or directory:",
            "An error ocurred attempting to rename the file or directory:",
            "An error ocurred attempting to create the file or directory:",
            "An error ocurred attempting to process USB GLUC commands:",
            "The clipboard was updated with the selected file.",
            "The clipboard was updated with the selected directory.",
            "The selected image isn't a valid icon.",
            "The selected image isn't 256x256 dimensions.",
        }
    };

    static const Dictionary Spanish =
    {
        Language::Spanish,
        {
            "Explorar tarjeta SD",
            "Explorar memoria de la consola",
            "Instalación USB",
            "Administrar contenidos del sistema",
            "Administrar tickets",
            "Navegador web",
            "Administrar cuentas de usuario",
            "Información de la consola",
            "Acerca de Goldleaf",
            "Explora archivos y carpetas de la tarjeta SD.",
            "Explora archivos y carpetas de la memoria de la consola.",
            "Instala NSPs via USB por medio de Goldtree u otros clientes PC.",
            "Explora todos los contenidos y títulos de la consola.",
            "Explora todos los tickets de títulos adquiridos o instalados.",
            "Navega por Internet por medio de los applets web de la consola.",
            "Selecciona una cuenta de usuario y adminístrala.",
            "Información sobre la tarjeta SD y la memoria de la consola.",
            "Logo, versión y tipo de ejecución de Goldleaf.",
            "Cancelar",
            "Tarjeta SD",
            "Explorador de memoria de la consola",
            "¿Qué partición de la memoria de la consola le gustaría explorar?",
            "PRODINFOF contiene varios contenidos de pruebas y otras cosas.",
            "NAND SAFE no contiene nada especialmente relevante.",
            "NAND SYSTEM contiene todos los títulos y contenidos del sistema.",
            "NAND USER contiene los títulos instalados en la memoria de la consola.",
            "PRODINFOF",
            "NAND SAFE",
            "NAND USER",
            "NAND SYSTEM",
            "Instalación USB",
            "Iniciando instalación USB...",
            "Contenidos del sistema",
            "Elige un almacenamiento para explorar sus contenidos.",
            "Administrador de tickets",
            "Buscando tickets en el sistema...",
            "Navagador web",
            "Las versiones no instaladas de Goldleaf usan el applet WifiAuth, que tiene algunas limitaciones.",
            "Elige página web para navegar por medio del applet.",
            "La página es incorrecta o inválida.",
            "Ha ocurrido un error al intentar ejecutar el applet web:",
            "Cuentas de usuario",
            "Procesando cuenta de usuario...",
            "Información de la consola",
            "Información sobre la tarjeta SD y la memoria de la consola.",
            "No se pudo detectar el tipo de ejecución de Goldleaf.",
            "Ejecutándose como un NRO de homebrew.",
            "Ejecutándose como un título instalado.",
            "Ejecutándose como Menú HOME (reemplazo).",
            "Esta carpeta esta vacía.",
            "Advertencia: acceso a la memoria de la consola",
            "¿Seguro que quiere editar o borrar contenido en la memoria de la consola?",
            "Tipo de archivo:",
            "instalable NSP",
            "ejecutable NRO",
            "ticket de contenidos",
            "tema NxTheme",
            "contenidos NCA",
            "archivo de control NACP",
            "imagen JPEG",
            "binary",
            "text",
            "file",
            "carpeta",
            "Tamaño:",
            "Instalar",
            "Ejecutar",
            "Importar",
            "Extraer",
            "Ver contenidos",
            "Reemplazar icono de usuario",
            "Ver texto",
            "Ver hexadecimal",
            "Copiar",
            "Eliminar",
            "Renombrar",
            "Opciones de archivo",
            "Instalación de NSP",
            "¿Dónde quiere instalar el NSP?",
            "Memoria de la consola",
            "¿Quiere ignorar la versión de firmware requerida del NSP?",
            "No hay espacio suficiente para instalar el NSP.",
            "Información de contenidos del NSP:",
            "El NSP contiene un título normal.",
            "El NSP contiene una actualización de un título.",
            "El NSP contiene contenido DLC.",
            "El NSP contiene otro tipo de contenido.",
            "El NSP parece ser oficial.",
            "El NSP parece ser un NSP de homebrew.",
            "El NSP tiene una ID de aplicación inválida o extraña.",
            "ID de aplicación:",
            "Nombre:",
            "Autor:",
            "Contenidos:",
            "El NSP contiene un ticket para ser importado:",
            "Generación de clave:",
            "versión desconocida",
            "El NSP no contiene ningún ticket.",
            "Ejecutar NRO",
            "¿Quiere cerrar Goldleaf y ejecutar este NRO?",
            "Sólo se pueden ejecutar NROs si Goldleaf e s un NRO.",
            "Importar ticket",
            "¿Quiere importar este ticket?",
            "Ha ocurrido un error al intentar importar el ticket:",
            "Instalar NxTheme",
            "No se encontró el NRO de NxThemesInstaller. El tema no se puede instalar.",
            "Nombre desconocido",
            "Autor desconocido",
            "Información de control NACP:",
            "Versión:",
            "¿Requiere una cuenta de usuario?",
            "Sí",
            "No",
            "Sí, pero la cuenta require tener una cuenta de los servicios de Nintendo.",
            "Valor desconocido",
            "¿Permite secar capturas de pantalla?",
            "¿Permite grabar vídeo?",
            "Sí (manual)",
            "Tipo de logo:",
            "Licensed by Nintendo",
            "Nintendo",
            "Reemplazar icono de cuenta de usuario",
            "¿Quiere reemplazar el icono de esta cuenta de usuario? Puede ser una acción peligrosa.",
            "El icono del usuario ha sido reemplazado con éxito.",
            "Ha ocurrido un error al intentar reemplazar el icono del usuario:",
            "Ejecución de payload",
            "¿Quiere reiniciar la consola ejecutando este archivo como payload?",
            "Eliminar archivo",
            "¿Le gustaría eliminar este archivo?",
            "El archivo fue eliminado con éxito.",
            "Elije un nuevo nombre para el archivo.",
            "Ya existe otro archivo o carpeta con el nombre especificado.",
            "Ha ocurrido un error al intentar renombrar el archivo.",
            "El archivo fue renombrado con éxito.",
            "What would you like to do with this directory?",
            "Opciones de carpeta",
            "Examinar",
            "Renombrar carpeta",
            "An error ocurred attempting to rename the directory:",
            "The directory was successfully renamed.",
            "Starting copy process...",
            "A directory (and all its contents) were successfully copied.",
            "File copy",
            "Another file exists with the same name. Would you like to overwrite it?",
            "Starting NSP installation...",
            "Installing NSP:",
            "Processing application records...",
            "Starting to write contents...",
            "Writing content",
            "of",
            "The NSP was successfully installed.",
            "Starting USB NSP installation...",
            "Waiting for USB connection...",
            "Plug this console with a USB-C cable to connect it with the PC.",
            "Error connecting via USB.",
            "USB connection was detected. Waiting for a request from the PC client...",
            "USB installation",
            "This NSP was requested:",
            "Would you like to install it?",
            "Average speed:",
            "The USB installation finalized successfully. The PC client can be closed.",
            "An invalid response was received. Retry the installation.",
            "Information",
            "Meta",
            "Program",
            "Data",
            "Control",
            "Html documents",
            "Legal information",
            "Selected content's information:",
            "Content type:",
            "regular title",
            "DLC content",
            "title update",
            "system title",
            "system data content",
            "other system contents",
            "Content size:",
            "Version number:",
            "update",
            "The content was successfully removed.",
            "An error ocurred attempting to remove the content:",
            "Title NSP export",
            "This title is equal or bigger than 4GB. Do not export it if you're on FAT32.",
            "Would you like to export this title as a NSP?",
            "NAND SYSTEM titles are blocked from being removed.",
            "Would you like to remove this content?",
            "Console contents",
            "This storage doesn't seem to have any contents.",
            "Browsing contents in this storage.",
            "Game cartridge",
            "Starting title export...",
            "Accessing system ticket database...",
            "Accessing title NCA contents...",
            "Decrypting and exporting contents...",
            "Exporting contents from console memory...",
            "Building NSP from exported contents...",
            "The title was successfully exported:",
            "An error ocurred attempting to export the title:",
            "No tickets were found on this console.",
            "Ticket options",
            "Ticket information:",
            "This ticket seems to be used by an installed content.",
            "This ticket seems to be unused.",
            "Would you like to remove this ticket?",
            "Are you sure you want to remove a ticket which seems to be used?",
            "The ticket was successfully removed from this console.",
            "An error ocurred attempting to remove the ticket:",
            "Change nickname",
            "View icon",
            "Delete account",
            "An error ocurred attempting to process the account:",
            "Selected user:",
            "Change the user's nickname",
            "The account's nickname was changed to",
            "An error ocurred attempting to rename the account:",
            "User account",
            "This icon has been exported here:",
            "Would you like to delete this account?",
            "The account was successfully deleted.",
            "An error ocurred attempting to delete the account:",
            "free",
            "Clipboard",
            "Would you like to paste the clipboard's content here?",
            "There is nothing selected to be copied.",
            "Select name to create a new file",
            "Another file or directory already has this name.",
            "A file was created:",
            "A directory was created:",
            "Reboot or shut down",
            "Would you like to reboot or shut down the console?",
            "A file or directory was copied. The clipboard was updated.",
            "Reboot",
            "Shut down",
            "Ok",
            "Title key;",
            "Signature type:",
            "Directory size:",
            "Select a new name to rename the file.",
            "Overwrite",
            "The file was successfully copied.",
            "Connection was established. Waiting for a NSP request from PC client...",
            "The PC client has finalized the connection.",
            "Content information",
            "Export",
            "Remove",
            "The content was successfully removed.",
            "An error ocurred attempting to remove the content:",
            "Browse both common and personalized tickets.",
            "An error ocurred attempting to rename the account: The name was too long.",
            "Select name to create a new directory.",
        }
    };
    
    static const Dictionary German =
    {
        Language::German,
        {
            "Durchsuche SD Karte",
            "Dursuche Internen Speicher",
            "USB Installation",
            "Verwalte installierte Inhalte",
            "Verwalte installierte Tickets",
            "Internetbrowser",
            "Verwalte Benutzer Accounts",
            "Konsoleninformationen",
            "Über Goldleaf",
            "Durchsuche die gesamten Inhalte der SD-Karte.",
            "Durchsuche die gesamten Inhalten des internen Speichers.",
            "Installiere NSPs via USB über Goldtree oder anderen Clients.",
            "Durchsuche alle installierten Inhalte auf der Konsole.",
            "Durchsuche alle installierten Tickets von gekauften oder installierten Inhalten.",
            "Surfe im Internet über das interne Web Applet.",
            "Wähle einen Benutzer und verwalte ihn.",
            "Zeigt Informationen über den internen Speicher und der SD-Karte.",
            "Zeigt Goldleaf´s Version, Modus und Logo.",
            "Abbrechen",
            "SD-Karte",
            "Interner Speicher",
            "Welche Partition des internen Speichers soll geöffnet werden?",
            "PRODINFOF beinhaltet einige Testlogs und andere Inhalte.",
            "NAND SAFE beinhaltet nichts relevantes.",
            "NAND SYSTEM beinhaltet alle Systemtitel und Inhalte.",
            "NAND USER beinhaltet alle installierten Inhalte auf dem internen Speicher.",
            "PRODINFOF",
            "NAND SAFE",
            "NAND USER",
            "NAND SYSTEM",
            "USB Installation",
            "Starte USB Installation...",
            "Verwaltung der Konsoleninhalte",
            "Wähle eine Partition aus um diese zu durchsuchen.",
            "Ticket Manager",
            "Suche nach importierten Tickets...",
            "Web Applet",
            "Nicht-installierte Version von Goldleaf benutzt das WifiAuth Web Applet; dies hat weniger Features.",
            "Gib eine Internetseite ein.",
            "Die ausgewählte Seite ist nicht kompatibel.",
            "Ein Fehler ist beim Starten aufgetreten:",
            "Benutzer Accounts",
            "Verarbeite Benutzer Account...",
            "Konsolen Information",
            "Zeigt den Speicher der SD-Karte und den internen Speicher.",
            "Es konnte nicht erkannt werden in welchem Modus Goldleaf läuft.",
            "Läuft als Homebrew NRO.",
            "Läuft als installierter Titel.",
            "Läuft als HOME Menu (qlaunch) Ersatz.",
            "Das Verzeichnis ist leer.",
            "Warnung: Zugriff auf den internen Speicher",
            "Bist du sicher, dass Dateien vom internen Speicher bearbeitet oder gelöscht werden sollen?",
            "Ausgewählter Dateityp:",
            "NSP",
            "NRO",
            "Inhaltsticket",
            "NxTheme Theme",
            "NCA Inhalt",
            "NACP Kontrolldatei",
            "JPEG Bild",
            "Binärdatei",
            "Text",
            "Datei",
            "Verzeichnis",
            "Dateigröße:",
            "Installiere",
            "Starte",
            "Importiere",
            "Entpacke",
            "Zeige Inhalte",
            "Ersetze Benutzerbild",
            "Zeige Text",
            "Zeige HEX",
            "Kopieren",
            "Löschen",
            "Umbenennen",
            "Dateioptionen",
            "NSP Installation",
            "Wohin soll die NSP installiert werden?",
            "Interner Speicher",
            "Soll die benötigte Firmware Version ignoriert werden?",
            "Es ist nicht genug Speicherplatz vorhanden.",
            "Informationen über die NSP:",
            "Die NSP beinhaltet einen Titel.",
            "Die NSP beinhaltet ein Titelupdate.",
            "Die NSP beinhaltet DLC Inhalte.",
            "Die NSP beinhaltet weitere Inhalte.",
            "Die NSP scheint eine offizielle zu sein.",
            "Die NSP scheint eine Homebrew NSP zu sein.",
            "Die NSP hat keine standardmäßige ID.",
            "Titel ID:",
            "Name:",
            "Author:",
            "Inhalte:",
            "Die NSP hat ein zu importierendes Ticket:",
            "Key Generation:",
            "Unbekannte Version",
            "Die NSP hat kein Ticket.",
            "NRO starten",
            "Möchtest du Goldleaf schließen und die ausgwählte NRO starten?",
            "NROs können nur gestartet werden, wenn Goldleaf als NRO gestartet wurde.",
            "Ticket importieren",
            "Möchtest du dieses Ticket importieren?",
            "Ein Fehler ist beim Importieren aufgetreten:",
            "NxTheme installieren",
            "NxThemesInstaller NRO wurde nicht gefunden. Das Theme kann nicht installiert werden.",
            "Unbekannter Name",
            "Unbekannter Author",
            "NACP Kontrolldaten Information:",
            "Version:",
            "Fragt nach einem Benutzer Account?",
            "Ja",
            "Nein",
            "Ja, aber der Account benötigt einen Nintendo Service Account.",
            "Unbekannter Wert",
            "Unterstützt Screenshots?",
            "Unterstützt Videoaufnahme?",
            "Ja (manuell)",
            "Logo Typ:",
            "Lizensiert von Nintendo",
            "Nintendo",
            "Account Bild ersetzen",
            "Möchtest du dein Bild vom Account ersetzen? Dies kann riskant sein.",
            "Das Bild wurde erfolgreich ersetzt.",
            "Ein Fehler beim Ersetzen aufgetreten:",
            "Payload starten",
            "Möchtest du neustarten und den ausgewähltn Payload starten?",
            "Datei löschen",
            "Ausgewählte Datei löschen?",
            "Datei erfolgreich gelöscht.",
            "Wähle einen neuen Dateinamen.",
            "Eine andere Datei oder Ordner hat bereits denselben Namen.",
            "Ein Fehler ist beim Umbenennen aufgetreten.",
            "Datei erfolgreich umbenannt.",
            "Was soll mit dem Ordner gemacht werden?",
            "Ordner Optionen",
            "Durchsuchen",
            "Ordner umbenennen",
            "Ein Fehler ist beim Umbenennen des Ordners aufgetreten:",
            "Ordner erfolgreich umbenannt.",
            "Starte Kopiervorgang...",
            "Ein Ordner (und alle Inhalte) wurden erfolgreich kopiert.",
            "Datei kopieren",
            "Eine andere Datei existiert bereits mit dem Namen. Soll diese überschrieben werden?",
            "Starte NSP Installation...",
            "Installiere NSP:",
            "Verarbeite Titel Inhalte...",
            "Bereite Inhalte vor...",
            "Übertrage Inhalte",
            "von",
            "Die NSP wurde erfolgreich installiert.",
            "Starte USB NSP Installation...",
            "Warte auf USB Verbindung...",
            "Verbinde die Konsole mit einem USB-C Kabel mit deinem PC.",
            "Fehler bei der USB Verbindung.",
            "USB Verbindung erkannt. Warte auf den PC Client...",
            "USB Installation",
            "Diese NSP wurde empfangen:",
            "Soll diese installiert werden?",
            "Durchschnittliche Geschwindigkeit:",
            "Die USB Installation erfolgreich durchgeführt. Der PC Client kann geschlossen werden.",
            "Eine ungültige Antwort wurde emfpangen. Wiederhole die Installation.",
            "Information",
            "Meta",
            "Programm",
            "Daten",
            "Control",
            "HTML Dokumente",
            "Rechtliche Informationen",
            "Informationen über den Inhalt:",
            "Inhaltstyp:",
            "Regulärer Titel",
            "DLC Inhalt",
            "Titel Update",
            "System Titel",
            "Systemdateien",
            "Andere Systeminhalte",
            "Größe:",
            "Versionsnummer:",
            "Update",
            "Der Inhalt wurde erfolgreich entfernt.",
            "Ein Fehler ist beim Löschen des Inhalts aufgetreten:",
            "NSP Titel exportieren",
            "Der Titel ist 4GB oder größer. Exportiere ihn nicht, wenn die SD Karte im FAT32 Format ist.",
            "Soll der Titel als NSP exportiert werden?",
            "Titel vom NAND SYSTEM können nicht gelöscht werden.",
            "Soll der Inhalt gelöscht werden?",
            "Konsolen Inhalte",
            "Es scheinen keine Inhalte vorhanden zu sein.",
            "Durchsuche die Inhalte im ausgewählten Speicher.",
            "Spiel Modul",
            "Starte exportieren des Titels...",
            "Greife auf Ticket Datenbank des Systems zu...",
            "Greife auf Titel NCA Inhalte zu...",
            "Entschlüssle und exportiere Inhalte...",
            "Exportiere Inhalte vom internen Speicher...",
            "Erstelle NSP von den exportierten Inhalten...",
            "Der Titel wurde erfolgreich exportiert:",
            "Ein Fehler beim Exportieren des Titels trat auf:",
            "Es wurden keine Tickets auf der Konsole gefunden.",
            "Ticket Optionen",
            "Ticket Informationen:",
            "Das Ticket wird von einem installierten Inhalt verwendet.",
            "Das Ticket scheint nicht verwendet zu werden.",
            "Soll das Ticket entfernt werden?",
            "Bist du sicher, dass das Ticket entfernt werden soll? Es wird von Inhalten benötigt.",
            "Das Ticket wurde erfolgreich entfernt.",
            "Ein Fehler beim Entfernen des Tickets trat auf:",
            "Ändere Benutzernamen",
            "Zeige Icon",
            "Lösche Account",
            "Ein Fehler beim Bearbeiten des Accounts trat auf:",
            "Ausgewählter Benutzer:",
            "Ändere den Benutzernamen",
            "Benutzername wurde geändert:",
            "Ein Fehler beim Umbenennen des Accounts trat auf:",
            "Benutzer Account",
            "Das Icon wurde exportiert nach:",
            "Soll der Account gelöscht werden?",
            "Account erfolgreich gelöscht.",
            "Ein Fehler beim Löschen des Accounts trat auf:",
            "frei",
            "Zwischenablage",
            "Soll der Inhalt aus der Zwischenablage hier eingefügt werden?",
            "Es wurde nichts zum Kopieren ausgewählt.",
            "Wähle einen Namen um eine neue Datei zu erstellen",
            "Eine andere Datei oder Ordner existiert bereits mit dem Namen.",
            "Datei wurde erstellt:",
            "Ein Ordner wurde erstellt:",
            "Neustart oder Ausschalten",
            "Soll die Konsole neustarten oder ausgeschaltet werden?",
            "Datei oder Ordner wurde kopiert. Die Zwischenable wurde aktualsiert.",
            "Neustart",
            "Ausschalten",
            "Ok",
            "Titel Key;",
            "Signatur Typ:",
            "Ordnergröße:",
            "Wähle einen neuen Namen um die umzubenennen.",
            "Überschreiben",
            "Datei wurde erfolgreich kopiert.",
            "Verbindung hergestellt. Warte aus NSP Datei vom PC Client...",
            "Der PC Client hat die Verbindung abgeschlossen.",
            "Inhaltsinformationen",
            "Exportieren",
            "Löschen",
            "Inhalt erfolgreich entfernt.",
            "Ein Fehler beim Löschen des Inhalts aufgetreten:",
            "Durchsuche normale und persönliche Tickets.",
            "Ein Fehler beim Umbenennen des Accounts trat auf: Der Name ist zu lang.",
            "Wähle einen Namen für den neuen Ordner.",
        }
    };

	static const Dictionary French =
    {
        Language::French,
        {
            "Parcourir la carte SD",
            "Parcourir la mémoire de la console",
            "Installations USB ",
            "Gérer le contenu de la console",
            "Gérer les tickets sur la console",
            "Naviguer sur Internet",
            "Gérer les comptes utilisateurs",
            "Voir les informations de la console",
            "A propos de Goldleaf",
            "Parcourir les fichiers et dossiers de la carte SD",
            "Parcourir la mémoire de la console et le contenu des partitions.",
            "Installer des NSPs via USB depuis Goldtree ou autres clients sur PC.",
            "Parcourir et naviguer tout le contenu ou tous les titres de la console.",
            "Parcourir tous les tickets du contenu acheté ou installé.",
            "Naviguer sur Internet en utilisant l'applet web de la console.",
            "Sélectionner un compte utilisateur pour le gérer.",
            "Voir des informations sur le statuts de la mémoire de la console et de la carte SD.",
            "Voir la version de Goldleaf, le mode de lancement et le logo",
            "Annuler",
            "Carte SD",
            "Mémoire de la console",
            "Quelle partition de la mémoire de la console voulez vous parcourir ?",
            "PRODINFOF contiens plusieurs journaux de tests et autres contenus.",
            "NAND SAFE ne contient rien d'exploitable.",
            "NAND SYSTEM contient tous les titres et contenus.",
            "NAND USER contient tout le contenu installé dans la mémoire de la console.",
            "PRODINFOF",
            "NAND SAFE",
            "NAND USER",
            "NAND SYSTEM",
            "Installation USB ",
            "Démarrage de l'installation USB...",
            "Gestionnaire du contenu de la console",
            "Sélectionnez le média de stockage pour en parcourir le contenu.",
            "Gestionnaire de tickets",
            "Recherche des tickets importés en cours...",
            "Applet web",
            "La version de Goldleaf non-installé utilise l'applet WifiAuth, qui a moins de fonctionnalités.",
            "Sélectionnez une page web à parcourir à travers l'applet web.",
            "La page sélectionnée n'est pas formatée correctement.",
            "Une erreur est apparue en essayant de lancer l'applet web:",
            "Comptes utilisateurs",
            "Traitement des comptes utilisateurs en cours...",
            "Informations de la console",
            "Voir l'état de la carte SD et de la mémoire de la console.",
            "Impossible de détecter dans quel mode est lancé Goldleaf.",
            "Lancé en tant qu'homebrew NRO.",
            "Lancé en tant que titre installé.",
            "Lancé en tant que remplacement de l'écran d'accueil (qlaunch).",
            "Ce dossier est vide.",
            "Attention: accès à la mémoire de la console",
            "Êtes vous sûr de vouloir écrire ou supprimer du contenu de la mémoire de la console?",
            "Sélectionnez le type de fichier:",
            "Package NSP",
            "Exécutable NRO",
            "ticket de contenu",
            "thème NxTheme ",
            "contenu NCA",
            "fichier de contrôle NACP",
            "Image JPEG",
            "binaire",
            "texte",
            "fichier",
            "dossier",
            "Taille du fichier:",
            "Installer",
            "Lancer",
            "Importer",
            "Extraire",
            "Voir le contenu",
            "Remplacer l’icône utilisateur",
            "Voir le texte",
            "Voir hex",
            "Copier",
            "Supprimer",
            "renommer",
            "Options du fichier",
            "Installation NSP",
            "Où voulez-vous installer le NSP ?",
            "Mémoire de la console",
            "Voulez-vous ignorer la version du firmware requise par le NSP ?",
            "Il n'y a pas assez de place pour installer le NSP.",
            "Information sur le contenu du NSP :",
            "Le NSP contient un titre (base).",
            "Le NSP contient une mise à jour de titre (update).",
            "Le NSP contient un DLC.",
            "Le NSP contient un autre type de contenu.",
            "Le NSP semble être officiel.",
            "Le NSP semble être un homebrew.",
            "le NSP a un ID d'application étrangement formaté.",
            "ID d'application:",
            "Nom:",
            "Auteur:",
            "Contenu:",
            "Le NSP a un ticket à importer:",
            "Génération de la clé:",
            "Version inconnue",
            "Le NSP n'a pas de ticket.",
            "Lancement du NRO",
            "Voulez-vous fermer Goldleaf et lancer ce NRO ?",
            "Les NROs ne peuvent être lancées que si Goldleaf est lancé en tant que NRO.",
            "Import de ticket",
            "Voulez-vous importer ce ticket ?",
            "Une erreur est survenue en tentant d'importer le ticket :",
            "Installation de NxTheme",
            "Le NRO de NxThemesInstaller est introuvable. Le thème ne peut pas être installé.",
            "Nom inconnu",
            "Auteur inconnu",
            "Information de contrôle NACP:",
            "Version:",
            "Demander le compte utilisateur ?",
            "Oui",
            "Non",
            "Oui, mais le compte utilisateur doit être lié aux services Nintendo.",
            "Valeur inconnue",
            "Supporte la prise de capture d'écran ?",
            "Supporte la prise de capture vidéo ?",
            "Oui (manuel)",
            "Type de logo :",
            "Licencié par Nintendo",
            "Nintendo",
            "Remplacement d'icône de compte utilisateur",
            "Voulez-vous remplacer l'icône de ce compte utilisateur ? Ceci peut être risqué.",
            "L'icône utilisateur a été remplacé avec succès.",
            "Une erreur est survenue en tentant de remplacer l’icône du compte utilisateur :",
            "Lancement du Payload",
            "Voulez-vous redémarrer la console en lançant ce fichier en tant que payload ?",
            "Suppression de fichier",
            "Voulez-vous supprimer ce fichier ?",
            "Le fichier a été supprimé avec succès.",
            "Sélectionnez un nouveau nom pour renommer ce fichier.",
            "Un autre fichier ou dossier porte déjà le même nom.",
            "Une erreur est survenue en tentant de renommer ce fichier.",
            "Le fichier a été renommé avec succès.",
            "Que voulez-vous faire avec ce dossier ?",
            "Options du dossier",
            "Parcourir",
            "Renommer le dossier",
            "Une erreur est survenue en tentant de renommer le dossier :",
            "Le dossier a été renommé avec succès.",
            "Démarrage du processus de copie...",
            "Un dossier (et tout son contenu) a été copié avec succès.",
            "Copier de fichier",
            "Un autre fichier avec le même nom existe. Voulez-vous l'écraser ?",
            "Démarrage de l'installation du NSP...",
            "Installation du NSP :",
            "Analyse de l'application...",
            "Démarrage de l'écriture du contenu...",
            "Écriture du contenu",
            "de",
            "Le NSP a été installé avec succès.",
            "Démarrage de l'installation USB du NSP...",
            "Attente de la connexion USB...",
            "Branchez votre console en USB sur votre PC.",
            "Erreur de connexion USB.",
            "La connexion USB a été détectée. En attente de la requête du client sur PC...",
            "Installation USB",
            "Ce NSP a été demandé :",
            "Voulez-vous l'installer ?",
            "Vitesse moyenne :",
            "L'installation USB s'est terminé avec succès. Le client sur PC peut être fermé.",
            "Une réponse invalide a été reçue. Réessayez l'installation.",
            "Information",
            "Méta",
            "Programme",
            "Données",
            "Contrôle",
            "Documents HTML",
            "Information légales ",
            "Informations sur le contenu sélectionné:",
            "Type de contenu :",
            "Titre de base",
            "DLC",
            "Mise à jour de titre (update)",
            "titre système",
            "contenu de données système",
            "autre type de contenu",
            "Taille du contenu :",
            "Numéro de version :",
            "mise à jour",
            "Le contenu a été supprimé avec succès.",
            "Une erreur est survenue en tentant de supprimer le contenu :",
            "Export de titre NSP",
            "La taille de ce titre est supérieure ou égale à 4GB. N'exportez pas si vous êtes en FAT32.",
            "Voulez-vous exporter ce titre en NSP ?",
            "Les titres NAND SYSTEM ne peuvent pas être supprimés.",
            "Voulez vous supprimer ce contenu ?",
            "Contenus de la console",
            "Cet emplacement de stockage à l'air d'être vide.",
            "Parcourir des contenus de cet emplacement.",
            "Cartouche de jeu",
            "Démarrage de l'export du titre...",
            "Accès à la base de donnée des tickets...",
            "Accès aux contenus NCA du titre...",
            "Décryptage et export du contenu...",
            "Export du contenu depuis la mémoire de la console...",
            "Construction du NSP à partir du contenu exporté...",
            "Le titre a été exporté avec succès :",
            "Une erreur est survenue en tentant d'exporter le titre:",
            "Aucun ticket n'a été trouvé sur la console.",
            "Options des tickets",
            "Informations sur le ticket :",
            "Ce ticket ne semble être utilisé par aucun titre.",
            "Ce ticket ne semble pas utilisé.",
            "Voulez-vous supprimer ce ticket ?",
            "Êtes-vous sûr de vouloir supprimer ce ticket qui semble être utilisé ?",
            "Le ticket a été supprimé avec succès.",
            "Une erreur est survenue en tentant de supprimer le ticket :",
            "Changement de pseudo",
            "Voir l'icône",
            "Suppression du compte",
            "Une erreur est survenue en tentant d'analyser le compte :",
            "Utilisateur sélectionné:",
            "Changer le pseudo de l'utilisateur",
            "Le pseudo du compte utilisateur a été changé en",
            "Une erreur est survenue en tentant de renommer le compte :",
            "Compte utilisateur",
            "Cet icône a été exporté ici :",
            "Voulez-vous supprimer ce compte ?",
            "Le compte a été supprimé avec succès.",
            "Une erreur est survenue en tentant de supprimer le compte :",
            "libre",
            "Presse-papier",
            "Voulez-vous coller le contenu du presse-papier ici ?",
            "Il n'y a rien de sélectionné pour la copie.",
            "Sélectionnez le nom du fichier à créer",
            "Un autre fichier ou dossier porte le même nom.",
            "Un fichier a été créé :",
            "Un dossier a été créé :",
            "Redémarrer ou éteindre",
            "Voulez-vous redémarrer ou éteindre la console ?",
            "Un fichier ou un dossier a été copié. Le presse-papier a été mis à jour.",
            "Redémarrer",
            "Éteindre",
            "Ok",
            "Clé du titre (titlekey);",
            "Type de signature :",
            "Taille du dossier :",
            "Sélectionnez un nouveau nom pour renommer le fichier.",
            "Écraser",
            "Le fichier a été copié avec succès.",
            "la connexion a été établie avec succès. En attente de la requête du client sur PC pour un NSP...",
            "Le client sur PC a finalisé la connexion.",
            "Information du contenu",
            "Exporter",
            "Supprimer",
            "Le contenu a été supprimé avec succès.",
            "Une erreur est survenue en tentant de supprimer le contenu:",
            "Parcourir les tickets et les tickets personnalisés.",
            "Une erreur est survenue en tentant de renommer le compte utilisateur: le nom est trop long.",
            "Sélectionnez un nom pour le nouveau dossier.",
        }
    };
	
    Dictionary GetDictionary();
    std::string GetDictionaryEntry(u32 Index);
}