
/*

    Goldleaf - Nintendo Switch homebrew multitool, for several purposes and with several features

    Copyright 2018 - 2019 Goldleaf project, developed by XorTroll
    This project is under the terms of GPLv3 license: https://github.com/XorTroll/Goldleaf/blob/master/LICENSE

*/

#pragma once
#include <gleaf/set/Settings.hpp>

namespace gleaf::set
{
    struct Dictionary
    {
        Language DictLanguage;
        std::vector<std::string> Strings;
    };

    static const Dictionary English =
    {
        Language::English,
        {
            "Browse SD card",
            "Browse console memory",
            "USB installations",
            "Manage console contents",
            "Manage console tickets",
            "Browse the Internet",
            "Manage user accounts",
            "View console information",
            "About Goldleaf",
            "Browse the SD card's files and directories.",
            "Browse console memory's partitions' files and directories.",
            "Install NSPs via USB from Goldtree or other PC clients.",
            "Browse and navigate through all contents or titles in the console.",
            "Browse all the tickets from purchased or installed contents.",
            "Browse the Internet using the console's web applet.",
            "Select a user account and manage it.",
            "View information about the state of the console's memory and the SD card.",
            "View Goldleaf's version, run mode and logo.",
            "Cancel",
            "SD card",
            "Console memory",
            "Which partition of the console memory would you like to browse?",
            "PRODINFOF contains several test logs and other contents.",
            "NAND SAFE doesn't contain anything relevant.",
            "NAND SYSTEM contains all system titles and contents.",
            "NAND USER contains content installed to console memory.",
            "PRODINFOF",
            "NAND SAFE",
            "NAND USER",
            "NAND SYSTEM",
            "USB installation",
            "Starting USB installation...",
            "Console contents manager",
            "Select storage to browse its contents.",
            "Ticket manager",
            "Searching for imported tickets...",
            "Web applet",
            "Non-installed title Goldleaf uses WifiAuth web applet, which has less features.",
            "Select web page to browse through the web applet.",
            "The selected web page is bad formatted.",
            "An error ocurred attempting to launch the web applet:",
            "User accounts",
            "Processing user account...",
            "Console information",
            "View SD card and console memory's state.",
            "Unable to detect on which mode Goldleaf is running.",
            "Running as a homebrew NRO.",
            "Running as an installed title.",
            "Running as a HOME Menu (qlaunch) replacement.",
            "This directory is empty.",
            "Warning: console memory access",
            "Are you sure you want to write or delete content from console memory?",
            "Selected file type:",
            "NSP package",
            "NRO executable",
            "content ticket",
            "NxTheme theme",
            "NCA content",
            "NACP control data",
            "JPEG image",
            "binary",
            "text",
            "file",
            "directory",
            "File size:",
            "Install",
            "Launch",
            "Import",
            "Extract",
            "View contents",
            "Replace user icon",
            "View text",
            "View hex",
            "Copy",
            "Delete",
            "Rename",
            "File options",
            "NSP installation",
            "Where would you like to install the NSP?",
            "Console memory",
            "Would you like to ignore the required firmware version of the NSP?",
            "There isn't enough size to install the NSP.",
            "NSP contents' information:",
            "The NSP contains a regular title.",
            "The NSP contains a title update.",
            "The NSP contains DLC content.",
            "The NSP contains other kinds of content.",
            "The NSP seems to be official.",
            "The NSP seems to be a homebrew NSP.",
            "The NSP has a weird-formatted application ID.",
            "Application ID:",
            "Name:",
            "Author:",
            "Contents:",
            "The NSP has a ticket to be imported:",
            "Key generation:",
            "unknown version",
            "The NSP doesn't have a ticket.",
            "NRO launch",
            "Would you like to close Goldleaf and launch this NRO?",
            "NROs can only be launched if Goldleaf is a NRO.",
            "Ticket import",
            "Would you like to import this ticket?",
            "An error ocurred attempting to import the ticket:",
            "NxTheme install",
            "NxThemesInstaller NRO was not found. The theme cannot be installed.",
            "Unknown name",
            "Unknown author",
            "NACP control data information:",
            "Version:",
            "Asks for an user account?",
            "Yes",
            "No",
            "Yes, but but the account needs to have a Nintendo services account.",
            "Unknown value",
            "Supports taking screenshots?",
            "Supports video capture?",
            "Yes (manual)",
            "Logo type:",
            "Licensed by Nintendo",
            "Nintendo",
            "Account icon replacement",
            "Would you like to replace the icon of this account? It can be a risky action.",
            "The user's icon was successfully replaced.",
            "An error ocurred attempting to replace the account's icon:",
            "Payload launch",
            "Would you like to reboot the console launching this file as a payload?",
            "File delete",
            "Would you like to delete this file?",
            "The file was successfully deleted.",
            "Select a new name to rename the file.",
            "Another file or directory already has that name.",
            "An error ocurred attempting to rename the file.",
            "The file was successfully renamed.",
            "What would you like to do with this directory?",
            "Directory options",
            "Browse",
            "Rename directory",
            "An error ocurred attempting to rename the directory:",
            "The directory was successfully renamed.",
            "Starting copy process...",
            "A directory (and all its contents) were successfully copied.",
            "File copy",
            "Another file exists with the same name. Would you like to overwrite it?",
            "Starting NSP installation...",
            "Installing NSP:",
            "Processing application records...",
            "Starting to write contents...",
            "Writing content",
            "of",
            "The NSP was successfully installed.",
            "Starting USB NSP installation...",
            "Waiting for USB connection...",
            "Plug this console with a USB-C cable to connect it with the PC.",
            "Error connecting via USB.",
            "USB connection was detected. Waiting for a request from the PC client...",
            "USB installation",
            "This NSP was requested:",
            "Would you like to install it?",
            "Average speed:",
            "The USB installation finalized successfully. The PC client can be closed.",
            "An invalid response was received. Retry the installation.",
            "Information",
            "Meta",
            "Program",
            "Data",
            "Control",
            "Html documents",
            "Legal information",
            "Selected content's information:",
            "Content type:",
            "regular title",
            "DLC content",
            "title update",
            "system title",
            "system data content",
            "other system contents",
            "Content size:",
            "Version number:",
            "update",
            "The content was successfully removed.",
            "An error ocurred attempting to remove the content:",
            "Title NSP export",
            "This title is equal or bigger than 4GB. Do not export it if you're on FAT32.",
            "Would you like to export this title as a NSP?",
            "NAND SYSTEM titles are blocked from being removed.",
            "Would you like to remove this content?",
            "Console contents",
            "This storage doesn't seem to have any contents.",
            "Browsing contents in this storage.",
            "Game cartridge",
            "Starting title export...",
            "Accessing system ticket database...",
            "Accessing title NCA contents...",
            "Decrypting and exporting contents...",
            "Exporting contents from console memory...",
            "Building NSP from exported contents...",
            "The title was successfully exported:",
            "An error ocurred attempting to export the title:",
            "No tickets were found on this console.",
            "Ticket options",
            "Ticket information:",
            "This ticket seems to be used by an installed content.",
            "This ticket seems to be unused.",
            "Would you like to remove this ticket?",
            "Are you sure you want to remove a ticket which seems to be used?",
            "The ticket was successfully removed from this console.",
            "An error ocurred attempting to remove the ticket:",
            "Change nickname",
            "View icon",
            "Delete account",
            "An error ocurred attempting to process the account:",
            "Selected user:",
            "Change the user's nickname",
            "The account's nickname was changed to",
            "An error ocurred attempting to rename the account:",
            "User account",
            "This icon has been exported here:",
            "Would you like to delete this account?",
            "The account was successfully deleted.",
            "An error ocurred attempting to delete the account:",
            "free",
            "Clipboard",
            "Would you like to paste the clipboard's content here?",
            "There is nothing selected to be copied.",
            "Select name to create a new file",
            "Another file or directory already has this name.",
            "A file was created:",
            "A directory was created:",
            "Reboot or shut down",
            "Would you like to reboot or shut down the console?",
            "A file or directory was copied. The clipboard was updated.",
            "Reboot",
            "Shut down",
            "Ok",
            "Title key;",
            "Signature type:",
            "Directory size:",
            "Select a new name to rename the file.",
            "Overwrite",
            "The file was successfully copied.",
            "Connection was established. Waiting for a NSP request from PC client...",
            "The PC client has finalized the connection.",
            "Content information",
            "Export",
            "Remove",
            "The content was successfully removed.",
            "An error ocurred attempting to remove the content:",
            "Browse both common and personalized tickets.",
            "An error ocurred attempting to rename the account: The name was too long.",
            "Select name to create a new directory.",
        }
    };

    static const Dictionary Spanish =
    {
        Language::Spanish,
        {
            "Explorar tarjeta SD",
            "Explorar memoria de la consola",
            "Instalación USB",
            "Administrar contenidos del sistema",
            "Administrar tickets",
            "Navegador web",
            "Administrar cuentas de usuario",
            "Información de la consola",
            "Acerca de Goldleaf",
            "Explora archivos y carpetas de la tarjeta SD.",
            "Explora archivos y carpetas de la memoria de la consola.",
            "Instala NSPs via USB por medio de Goldtree u otros clientes PC.",
            "Explora todos los contenidos y títulos de la consola.",
            "Explora todos los tickets de títulos adquiridos o instalados.",
            "Navega por Internet por medio de los applets web de la consola.",
            "Selecciona una cuenta de usuario y adminístrala.",
            "Información sobre la tarjeta SD y la memoria de la consola.",
            "Logo, versión y tipo de ejecución de Goldleaf.",
            "Cancelar",
            "Tarjeta SD",
            "Explorador de memoria de la consola",
            "¿Qué partición de la memoria de la consola le gustaría explorar?",
            "PRODINFOF contiene varios contenidos de pruebas y otras cosas.",
            "NAND SAFE no contiene nada especialmente relevante.",
            "NAND SYSTEM contiene todos los títulos y contenidos del sistema.",
            "NAND USER contiene los títulos instalados en la memoria de la consola.",
            "PRODINFOF",
            "NAND SAFE",
            "NAND USER",
            "NAND SYSTEM",
            "Instalación USB",
            "Iniciando instalación USB...",
            "Contenidos del sistema",
            "Elige un almacenamiento para explorar sus contenidos.",
            "Administrador de tickets",
            "Buscando tickets en el sistema...",
            "Navagador web",
            "Las versiones no instaladas de Goldleaf usan el applet WifiAuth, que tiene algunas limitaciones.",
            "Elige página web para navegar por medio del applet.",
            "La página es incorrecta o inválida.",
            "Ha ocurrido un error al intentar ejecutar el applet web:",
            "Cuentas de usuario",
            "Procesando cuenta de usuario...",
            "Información de la consola",
            "Información sobre la tarjeta SD y la memoria de la consola.",
            "No se pudo detectar el tipo de ejecución de Goldleaf.",
            "Ejecutándose como un NRO de homebrew.",
            "Ejecutándose como un título instalado.",
            "Ejecutándose como Menú HOME (reemplazo).",
            "Esta carpeta esta vacía.",
            "Advertencia: acceso a la memoria de la consola",
            "¿Seguro que quiere editar o borrar contenido en la memoria de la consola?",
            "Tipo de archivo:",
            "instalable NSP",
            "ejecutable NRO",
            "ticket de contenidos",
            "tema NxTheme",
            "contenidos NCA",
            "archivo de control NACP",
            "imagen JPEG",
            "binary",
            "text",
            "file",
            "carpeta",
            "Tamaño:",
            "Instalar",
            "Ejecutar",
            "Importar",
            "Extraer",
            "Ver contenidos",
            "Reemplazar icono de usuario",
            "Ver texto",
            "Ver hexadecimal",
            "Copiar",
            "Eliminar",
            "Renombrar",
            "Opciones de archivo",
            "Instalación de NSP",
            "¿Dónde quiere instalar el NSP?",
            "Memoria de la consola",
            "¿Quiere ignorar la versión de firmware requerida del NSP?",
            "No hay espacio suficiente para instalar el NSP.",
            "Información de contenidos del NSP:",
            "El NSP contiene un título normal.",
            "El NSP contiene una actualización de un título.",
            "El NSP contiene contenido DLC.",
            "El NSP contiene otro tipo de contenido.",
            "El NSP parece ser oficial.",
            "El NSP parece ser un NSP de homebrew.",
            "El NSP tiene una ID de aplicación inválida o extraña.",
            "ID de aplicación:",
            "Nombre:",
            "Autor:",
            "Contenidos:",
            "El NSP contiene un ticket para ser importado:",
            "Generación de clave:",
            "versión desconocida",
            "El NSP no contiene ningún ticket.",
            "Ejecutar NRO",
            "¿Quiere cerrar Goldleaf y ejecutar este NRO?",
            "Sólo se pueden ejecutar NROs si Goldleaf e s un NRO.",
            "Importar ticket",
            "¿Quiere importar este ticket?",
            "Ha ocurrido un error al intentar importar el ticket:",
            "Instalar NxTheme",
            "No se encontró el NRO de NxThemesInstaller. El tema no se puede instalar.",
            "Nombre desconocido",
            "Autor desconocido",
            "Información de control NACP:",
            "Versión:",
            "¿Requiere una cuenta de usuario?",
            "Sí",
            "No",
            "Sí, pero la cuenta require tener una cuenta de los servicios de Nintendo.",
            "Valor desconocido",
            "¿Permite secar capturas de pantalla?",
            "¿Permite grabar vídeo?",
            "Sí (manual)",
            "Tipo de logo:",
            "Licensed by Nintendo",
            "Nintendo",
            "Reemplazar icono de cuenta de usuario",
            "¿Quiere reemplazar el icono de esta cuenta de usuario? Puede ser una acción peligrosa.",
            "El icono del usuario ha sido reemplazado con éxito.",
            "Ha ocurrido un error al intentar reemplazar el icono del usuario:",
            "Ejecución de payload",
            "¿Quiere reiniciar la consola ejecutando este archivo como payload?",
            "Eliminar archivo",
            "¿Le gustaría eliminar este archivo?",
            "The file was successfully deleted.",
            "Select a new name to rename the file.",
            "Another file or directory already has that name.",
            "An error ocurred attempting to rename the file.",
            "The file was successfully renamed.",
            "What would you like to do with this directory?",
            "Directory options",
            "Browse",
            "Rename directory",
            "An error ocurred attempting to rename the directory:",
            "The directory was successfully renamed.",
            "Starting copy process...",
            "A directory (and all its contents) were successfully copied.",
            "File copy",
            "Another file exists with the same name. Would you like to overwrite it?",
            "Starting NSP installation...",
            "Installing NSP:",
            "Processing application records...",
            "Starting to write contents...",
            "Writing content",
            "of",
            "The NSP was successfully installed.",
            "Starting USB NSP installation...",
            "Waiting for USB connection...",
            "Plug this console with a USB-C cable to connect it with the PC.",
            "Error connecting via USB.",
            "USB connection was detected. Waiting for a request from the PC client...",
            "USB installation",
            "This NSP was requested:",
            "Would you like to install it?",
            "Average speed:",
            "The USB installation finalized successfully. The PC client can be closed.",
            "An invalid response was received. Retry the installation.",
            "Information",
            "Meta",
            "Program",
            "Data",
            "Control",
            "Html documents",
            "Legal information",
            "Selected content's information:",
            "Content type:",
            "regular title",
            "DLC content",
            "title update",
            "system title",
            "system data content",
            "other system contents",
            "Content size:",
            "Version number:",
            "update",
            "The content was successfully removed.",
            "An error ocurred attempting to remove the content:",
            "Title NSP export",
            "This title is equal or bigger than 4GB. Do not export it if you're on FAT32.",
            "Would you like to export this title as a NSP?",
            "NAND SYSTEM titles are blocked from being removed.",
            "Would you like to remove this content?",
            "Console contents",
            "This storage doesn't seem to have any contents.",
            "Browsing contents in this storage.",
            "Game cartridge",
            "Starting title export...",
            "Accessing system ticket database...",
            "Accessing title NCA contents...",
            "Decrypting and exporting contents...",
            "Exporting contents from console memory...",
            "Building NSP from exported contents...",
            "The title was successfully exported:",
            "An error ocurred attempting to export the title:",
            "No tickets were found on this console.",
            "Ticket options",
            "Ticket information:",
            "This ticket seems to be used by an installed content.",
            "This ticket seems to be unused.",
            "Would you like to remove this ticket?",
            "Are you sure you want to remove a ticket which seems to be used?",
            "The ticket was successfully removed from this console.",
            "An error ocurred attempting to remove the ticket:",
            "Change nickname",
            "View icon",
            "Delete account",
            "An error ocurred attempting to process the account:",
            "Selected user:",
            "Change the user's nickname",
            "The account's nickname was changed to",
            "An error ocurred attempting to rename the account:",
            "User account",
            "This icon has been exported here:",
            "Would you like to delete this account?",
            "The account was successfully deleted.",
            "An error ocurred attempting to delete the account:",
            "free",
            "Clipboard",
            "Would you like to paste the clipboard's content here?",
            "There is nothing selected to be copied.",
            "Select name to create a new file",
            "Another file or directory already has this name.",
            "A file was created:",
            "A directory was created:",
            "Reboot or shut down",
            "Would you like to reboot or shut down the console?",
            "A file or directory was copied. The clipboard was updated.",
            "Reboot",
            "Shut down",
            "Ok",
            "Title key;",
            "Signature type:",
            "Directory size:",
            "Select a new name to rename the file.",
            "Overwrite",
            "The file was successfully copied.",
            "Connection was established. Waiting for a NSP request from PC client...",
            "The PC client has finalized the connection.",
            "Content information",
            "Export",
            "Remove",
            "The content was successfully removed.",
            "An error ocurred attempting to remove the content:",
            "Browse both common and personalized tickets.",
            "An error ocurred attempting to rename the account: The name was too long.",
            "Select name to create a new directory.",
        }
    };

    Dictionary GetDictionary();
    std::string GetDictionaryEntry(u32 Index);
}